---
- hosts: masters
  tasks:
  - name: 1.Disabling Swap on all nodes
    shell: swapoff -a

  - name: 2.Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'
